### ISSUE TITLE
Publish on Bower/WC 

### ISSUE THREAD

**Issue by nicholaswmin** [nicholaswmin/editable-list#5]
## Todos

- [ ] Publish on Bower/Create a proper first release
- [ ] Test installation of element to new project
- [ ] Ensure no unnecessary deps are installed/loaded under a usual scenario
- [ ] Publish on [WebComponents.org][1]

[1]: https://www.webcomponents.org/
